"""Interactive CLI setup wizard.

Walks a new user through populating .env without making them edit a file by
hand. Validates credentials against the live Looki API before writing, and
auto-generates a strong ORIGIN_SHARED_SECRET when one isn't already set.

Run via: ``python main.py setup`` or ``python -m looki_mcp.setup_wizard``
"""

from __future__ import annotations

import asyncio
import getpass
import secrets
import sys
from pathlib import Path

import httpx

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = PROJECT_ROOT / ".env"


def _read_existing_env() -> dict[str, str]:
    """Read existing .env into a dict. Returns {} if no .env yet."""
    if not ENV_PATH.exists():
        return {}
    result: dict[str, str] = {}
    for line in ENV_PATH.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            k, _, v = line.partition("=")
            result[k.strip()] = v.strip()
    return result


def _prompt(label: str, default: str | None = None) -> str:
    """Visible prompt with an optional default. Empty input keeps the default."""
    suffix = f" [{default}]" if default else ""
    value = input(f"  {label}{suffix}: ").strip()
    return value or (default or "")


def _prompt_secret(label: str, existing: str | None = None) -> str:
    """Hidden prompt for sensitive input. Empty input keeps the existing value."""
    if existing:
        masked = existing[:6] + "…" + existing[-4:] if len(existing) > 12 else "***"
        print(f"  {label} [keep existing: {masked}]")
        value = getpass.getpass("    (paste a new value, or press Enter to keep): ").strip()
        return value or existing
    return getpass.getpass(f"  {label}: ").strip()


async def _validate(base_url: str, api_key: str) -> tuple[bool, str]:
    """Hit the verify endpoint and /me to confirm both inputs are valid."""
    verify_url = f"https://open.looki.ai/api/v1/verify?endpoint={base_url}"
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            r = await client.get(verify_url)
            if r.status_code != 200 or r.json().get("status") != "ok":
                return False, f"Base URL rejected by Looki (HTTP {r.status_code})"
    except Exception as exc:
        return False, f"Could not reach Looki verify endpoint: {exc}"

    try:
        async with httpx.AsyncClient(base_url=base_url, timeout=10.0) as client:
            r = await client.get(
                "/me", headers={"X-API-Key": api_key, "Accept": "application/json"}
            )
            if r.status_code != 200:
                return False, f"API call to /me failed (HTTP {r.status_code})"
            body = r.json()
            if body.get("code") != 0:
                return False, f"API rejected request: {body.get('detail', 'unknown')}"
            user = body.get("data", {}).get("user", {})
            name = f"{user.get('first_name', '')} {user.get('last_name', '')}".strip()
            return True, f"verified — account: {name or 'unknown'}"
    except Exception as exc:
        return False, f"API call failed: {exc}"


def _write_env(values: dict[str, str]) -> None:
    """Write values to .env. Preserves unknown keys from any existing file.

    Empty string values are written as a blank assignment (KEY=) so the user
    can see which optional vars are unset rather than having them disappear.
    """
    existing = _read_existing_env()
    existing.update(values)

    ordered_keys = [
        ("LOOKI_BASE_URL", "Your Looki API base URL — https://web.looki.ai/api-keys"),
        ("LOOKI_API_KEY", "Your Looki API key (starts with lk-)"),
        ("LOOKI_PORT", "HTTP port for this server"),
        ("LOOKI_USER_TIMEZONE", "IANA timezone name (e.g. America/New_York). Empty = UTC."),
        ("LOOKI_MCP_BASE_URL", "Public URL of this server, used for icon display"),
        ("ORIGIN_SHARED_SECRET", "Shared secret required in the x-origin-secret header"),
        ("LOOKI_TLS_CERT_PATH", "Optional: path to TLS cert PEM for direct HTTPS"),
        ("LOOKI_TLS_KEY_PATH", "Optional: path to TLS key PEM for direct HTTPS"),
    ]

    lines: list[str] = [
        "# Generated by 'python main.py setup' — re-run any time to update.",
        "# This file contains secrets. It is gitignored. Permissions: 600.",
        "",
    ]
    written: set[str] = set()
    for key, comment in ordered_keys:
        if key in existing:
            lines.append(f"# {comment}")
            lines.append(f"{key}={existing[key]}")
            lines.append("")
            written.add(key)
    # Preserve any custom keys the user added by hand
    for key, val in existing.items():
        if key not in written:
            lines.append(f"{key}={val}")

    ENV_PATH.write_text("\n".join(lines))
    ENV_PATH.chmod(0o600)


async def main() -> int:
    print()
    print("looki-mcp setup")
    print("=" * 60)
    print()
    print("This wizard configures your Looki credentials and writes .env in")
    print(f"  {PROJECT_ROOT}")
    print()
    print("If you don't have credentials yet, generate them at:")
    print("  https://web.looki.ai/api-keys")
    print()
    print("Re-run 'python main.py setup' any time to change these values.")
    print()

    existing = _read_existing_env()
    if existing:
        print(f"Found existing .env with {len(existing)} setting(s); shown values are defaults.")
        print()

    print("1. Looki credentials (required)")
    print("-" * 60)

    base_url = _prompt(
        "Looki API base URL (https://...)", default=existing.get("LOOKI_BASE_URL")
    )
    while not base_url:
        print("  (required — copy it from https://web.looki.ai/api-keys)")
        base_url = _prompt("Looki API base URL")

    api_key = _prompt_secret("Looki API key (starts with lk-)", existing.get("LOOKI_API_KEY"))
    while not api_key or not api_key.startswith("lk-"):
        print("  (required, and must start with 'lk-')")
        api_key = _prompt_secret("Looki API key")

    print()
    print("Verifying with Looki…")
    ok, msg = await _validate(base_url, api_key)
    if ok:
        print(f"  ✓ {msg}")
    else:
        print(f"  ✗ {msg}")
        print()
        confirm = input("Save anyway? [y/N]: ").strip().lower()
        if confirm not in ("y", "yes"):
            print("Setup canceled. Re-run when you have correct values.")
            return 1

    print()
    print("2. Optional settings (press Enter to accept defaults)")
    print("-" * 60)

    port = _prompt("HTTP port for this server", default=existing.get("LOOKI_PORT", "3456"))
    timezone = _prompt(
        "Your timezone (IANA name, e.g. America/New_York; blank = UTC)",
        default=existing.get("LOOKI_USER_TIMEZONE", ""),
    )
    public_url = _prompt(
        "Public URL of this server (used for the Looki icon in MCP clients)",
        default=existing.get("LOOKI_MCP_BASE_URL", ""),
    )

    print()
    print("3. Origin secret")
    print("-" * 60)
    print("ORIGIN_SHARED_SECRET requires an `x-origin-secret` header on every")
    print("request. Strongly recommended if your server is reachable from the public")
    print("internet — see README's 'Origin Secret' section for details.")
    print()

    if existing.get("ORIGIN_SHARED_SECRET"):
        keep = input("  Keep existing origin secret? [Y/n]: ").strip().lower()
        if keep in ("", "y", "yes"):
            origin_secret = existing["ORIGIN_SHARED_SECRET"]
            print("  → keeping existing value")
        else:
            origin_secret = secrets.token_hex(32)
            print("  → generated new origin secret")
    else:
        gen = input("  Auto-generate an origin secret now? [Y/n]: ").strip().lower()
        if gen in ("", "y", "yes"):
            origin_secret = secrets.token_hex(32)
            print("  → generated")
        else:
            origin_secret = ""
            print("  → skipped (server will accept all requests)")

    values = {
        "LOOKI_BASE_URL": base_url,
        "LOOKI_API_KEY": api_key,
        "LOOKI_PORT": port,
        "LOOKI_USER_TIMEZONE": timezone,
        "LOOKI_MCP_BASE_URL": public_url,
        "ORIGIN_SHARED_SECRET": origin_secret,
    }
    _write_env(values)

    print()
    print(f"✓ Saved to {ENV_PATH} (mode 600)")
    if origin_secret:
        print()
        print("┌─ Origin secret ──────────────────────────────────────────────┐")
        print(f"│ {origin_secret} │")
        print("└──────────────────────────────────────────────────────────────┘")
        print()
        print("Add this exact value to your MCP client's request headers as")
        print("`x-origin-secret`. It's also stored in your .env file.")
    print()
    print("Next steps:")
    print("  1. Start the server:    python main.py")
    print("  2. Add to your MCP client (claude.ai, Claude Desktop, ChatGPT, etc.)")
    print("     using your server URL — and the origin secret above if you set one.")
    print()
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
